### PR TITLE
Updated debian directory

### PR DESCRIPTION
**Pull request by zgrimshell**
Now building and using properly python3

### CODE REVIEW

**Comment by hrnr** [comment]
Hi, have you thought about updating debian package? Because debian package in repo is very old and it is not working since apiv2 is down.

**Comment by zgrimshell** [comment]
@hrnr yes, new version of pafy and mps-youtube should hit unstable in next 24 hours if some problem doesn't pop out. The migration process to testing is 10 days if there is no problem. For Debian Jessie (the current stable) I will need to wait next round of jessie-updates (probably for 8.2 as 8.1 windows is closed) or to prepare backports (I'll investigate options). Also with debian dirs in place you can build packages yourself (and they will be the same as the official ones).

**Comment by hrnr** [comment]
Great news! I'm glad mps-youtube is not dead on debian. I've made jessie packages with pbuilder and they work like a charm. thanks

**Comment by zgrimshell** [comment]
Not dead at all. The packages were always updated in debian mentors and targeting debian experimental but they were not uploaded to it during the Jessie freeze and now I just merged all commits into one. Glad to help and good to know that it works.

**Pull request merged**
