### PR TITLE
Dead code removal / Minor bug fixes / Minor improvement

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by ids1024** [comment]
@np1 What purpose does this code serve? Mpsyt seems to run without it.

    __main__.Playlist = Playlist
    __main__.Video = Video

**Comment by np1** [comment]
Good work, thanks a lot for the cleanup :)

I can recall that without those two lines the pickle module was not able unpickle the saved playlist data, Feel free to play around with it!

**Comment by ids1024** [comment]
If so there should probably be a comment in the code, because it is not obvious at all.

**Comment by np1** [comment]
I just tried removing the two lines and was unable to recreate the pickle error. Maybe they can be removed then. I tested with Python 2 and 3 running mpsyt directly and running after having installing with setup.py

**Pull request merged**
